#!/bin/sh

f=.env.production.local

printf  >"$f" 'NUXT_PUBLIC_GITHASH="%s"\n'   "$(printf %s "$SOURCE_VERSION" | head -c7)"
printf >>"$f" 'NUXT_PUBLIC_TIMESTAMP="%s"\n' "$(TZ=Europe/Stockholm date +"%F %T %Z")"
