#!/bin/sh

f=.env.production.local

printf  >"$f" 'NUXT_PUBLIC_GITHASH="%s"\n'   "$(git rev-parse --short HEAD)"
printf >>"$f" 'NUXT_PUBLIC_TIMESTAMP="%s"\n' "$(TZ=Europe/Stockholm date +"%F %T %Z")"
