const treeGroupMap: Record<string, string> = {
  Berberisbär: 'berry',
  Blåbär: 'berry',
  Blåhallon: 'berry',
  Jordgubbar: 'berry',
  Krusbär: 'berry',
  Körsbärskornell: 'berry',
  Lingon: 'berry',
  Björnbär: 'berry-blackberry',
  Aronia: 'berry-chokeberry',
  'Röda vinbär': 'berry-currant',
  Vinbär: 'berry-currant',
  'Svarta vinbär': 'berry-blackcurrant',
  Fläder: 'berry-elder',
  Fläderblom: 'berry-elder',
  Fläderbär: 'berry-elder',
  Bocktörne: 'berry-goji',
  Gojibär: 'berry-goji',
  Mullbär: 'berry-mullberry',
  'Svart mullbär': 'berry-mullberry',
  Hallon: 'berry-raspberry',
  Nypon: 'berry-rosehip',
  Rönnbär: 'berry-rowanberry',
  Havtorn: 'berry-seabuckthorn',
  Krikon: 'tree-sloeberry',
  Slånbär: 'tree-sloeberry',
  Smultron: 'berry-wildstrawberry',
  Mandel: 'nut',
  Hasselnöt: 'nut-hazelnut',
  Kastanj: 'nut-sweetchestnut',
  Valnöt: 'nut-walnut',
  Äpple: 'tree-apple',
  Bigarråer: 'tree-cherry',
  Körsbär: 'tree-cherry',
  Surkörsbär: 'tree-cherry',
  Päron: 'tree-pear',
  Körsbärsplommon: 'tree-plum',
  Mirabell: 'tree-plum',
  Mirabellplommon: 'tree-plum',
  Plommon: 'tree-plum',
  Kvitten: 'tree-quince',
  Rosenkvitten: 'tree-quince',
  Rabarber: 'tree-rhubarb',
  Humle: 'herb',
  Mynta: 'herb',
  Kamomill: 'herb-chamomille',
  Körvel: 'herb-chervil',
  Brännässla: 'herb-nettle',
  Ramslök: 'herb-wildgarlic',
  'Annan sort': 'tree',
}

export default treeGroupMap
