name: Build

on:
  push:
    branches-ignore:
      - production
  pull_request:
    branches-ignore:
      - production
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Build
        run: |
          NODE_OPTIONS=--openssl-legacy-provider npm ci
          NODE_OPTIONS=--openssl-legacy-provider npm run-script build
